import React from 'react';
import { ScrollView, Text, StyleSheet, View } from 'react-native';

export default function TermsOfServiceScreen() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Terms of Service</Text>
      <Text style={styles.lastUpdated}>Last Updated: May 2026</Text>

      <View style={styles.section}>
        <Text style={styles.heading}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By accessing or using the Fit My Room mobile application ("App"), you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you may not access or use the App.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>2. Description of Service</Text>
        <Text style={styles.paragraph}>
          Fit My Room provides an augmented reality (AR) and artificial intelligence tool that attempts to calculate spatial dimensions and render 3D visualizations of furniture based on photos you provide.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>3. Disclaimer of Warranties</Text>
        <Text style={styles.paragraph}>
          <Text style={styles.bold}>The services and features are provided "as is" and "as available".</Text> Fit My Room relies on complex computer vision algorithms that may produce inaccurate or flawed measurements. You acknowledge that any dimensions, spatial layouts, or visual representations generated by the App are <Text style={styles.bold}>estimates only</Text> and should not be solely relied upon for purchasing decisions, construction, or critical spatial planning. We strongly recommend manually verifying all measurements with traditional tools.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>4. User Content and Privacy</Text>
        <Text style={styles.paragraph}>
          By uploading photos to the App, you grant us a license to process these images solely for the purpose of providing the service to you. You warrant that you have the right to upload any photos you submit. Please review our Privacy Policy for details on how we handle your personal data and camera permissions.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>5. Acceptable Use</Text>
        <Text style={styles.paragraph}>
          You agree not to use the App to:
        </Text>
        <Text style={styles.bullet}>• Violate any local, state, national, or international law.</Text>
        <Text style={styles.bullet}>• Upload images containing explicit, illegal, or unauthorized content.</Text>
        <Text style={styles.bullet}>• Attempt to reverse engineer, decompile, or hack the AI services.</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>6. Limitation of Liability</Text>
        <Text style={styles.paragraph}>
          In no event shall Fit My Room, its creators, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, resulting from your use of the App or reliance on its generated measurements.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>7. Changes to Terms</Text>
        <Text style={styles.paragraph}>
          We reserve the right to modify these terms at any time. We will notify you of any material changes by updating the "Last Updated" date at the top of this document or via in-app notification.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  content: {
    padding: 24,
    paddingBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0b1c30',
    marginBottom: 8,
  },
  lastUpdated: {
    fontSize: 14,
    color: '#76777d',
    marginBottom: 32,
    fontStyle: 'italic',
  },
  section: {
    marginBottom: 24,
  },
  heading: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0b1c30',
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 24,
    color: '#45464d',
  },
  bold: {
    fontWeight: '700',
    color: '#0b1c30',
  },
  bullet: {
    fontSize: 15,
    lineHeight: 24,
    color: '#45464d',
    marginLeft: 8,
    marginTop: 4,
  },
});
